import test from 'node:test';
import assert from 'node:assert/strict';
import worker, {gradeObjective,validateTask,validateProfile,safeTask,sourceRepair} from '../src/worker.js';
const task={title:'Opinião',instruction:'Interpreta.',source:'La rapidez no basta. La inclusión importa. Hay alternativas.',minutes:10,minWords:0,maxWords:0,questions:[{prompt:'¿Qué importa?',choices:['La inclusión','Nada','Todo'],correctIndex:0,evidence:'La inclusión importa.',explanation:'La fuente lo dice.'},{prompt:'¿Basta la rapidez?',choices:['Sí','No','Siempre'],correctIndex:1,evidence:'La rapidez no basta.',explanation:'No es suficiente.'},{prompt:'¿Hay alternativas?',choices:['No','Quizás','Sí'],correctIndex:2,evidence:'Hay alternativas.',explanation:'El texto lo afirma.'}]};
test('generated answer keys must be backed by a literal passage',()=>{assert.equal(validateTask(task,'reading'),task);assert.throws(()=>validateTask({...task,questions:task.questions.map(q=>({...q,evidence:'Esto no está en la fuente.'}))},'reading'));});
test('objective grade uses stored key and rejects incomplete responses',()=>{assert.equal(gradeObjective(task,[0,1,2]).correct,3);assert.equal(gradeObjective(task,[2,1,0]).correct,1);assert.throws(()=>gradeObjective(task,[0,null,2]));assert.throws(()=>gradeObjective(task,[0,1]));assert.throws(()=>gradeObjective(task,[0,1,3]));});
test('private API blocks access without touching the database',async()=>{const response=await worker.fetch(new Request('https://habla.test/api/profiles'),{APP_ACCESS_KEY:'test-access'});assert.equal(response.status,401);});
test('cross-origin writes cannot trigger AI or change records',async()=>{const response=await worker.fetch(new Request('https://habla.test/api/tasks',{method:'POST',headers:{Origin:'https://untrusted.test'},body:'{}'}),{APP_ACCESS_KEY:'test-access'});assert.equal(response.status,403);});
test('profiles reject arbitrary identifiers',()=>{assert.equal(validateProfile('luiz'),'luiz');assert.throws(()=>validateProfile('admin'));});

test('API hides audio stimulus and answer keys for writing mediation as well as listening',()=>{for(const kind of ['writing','listening']){const safe=safeTask({id:'test',kind,payload:JSON.stringify({...task,sourceMode:'audio',answerKey:[0],review:{approved:true}})}).payload;assert.equal(safe.source,'');assert.equal(safe.answerKey,undefined);for(const question of safe.questions){assert.equal(question.correctIndex,undefined);assert.equal(question.evidence,undefined);assert.equal(question.explanation,undefined);}}});
test('reading API preserves the text while hiding correction fields',()=>{const safe=safeTask({kind:'reading',payload:JSON.stringify(task)}).payload;assert.equal(safe.source,task.source);assert.equal(safe.questions[0].correctIndex,undefined);});

test('export cannot bypass protection of pending answer keys or oral sources',async()=>{const rows=[{id:'reading',kind:'reading',payload:JSON.stringify(task)},{id:'writing',kind:'writing',payload:JSON.stringify({...task,sourceMode:'audio'})}];const DB={prepare(sql){return {async all(){return {results:sql.includes('FROM tasks')?rows:[]};}};}};const r=await worker.fetch(new Request('https://habla.test/api/export'),{LOCAL_DEV:'true',DB});assert.equal(r.status,200);const d=await r.json();assert.equal(d.tasks[0].payload.questions[0].correctIndex,undefined);assert.equal(d.tasks[1].payload.source,'');});

test('repair keeps multiline stimulus on server without putting newlines in strict enum literals',()=>{const schema={properties:{source:{type:'string'},title:{type:'string'}}};const original='Primer párrafo.\n\nSegundo párrafo.';const repair=sourceRepair(schema,original);assert.deepEqual(repair.schema.properties.source.enum,['']);assert.equal(repair.restore({source:'',title:'Texto'}).source,original);assert.equal(schema.properties.source.enum,undefined);assert.equal(sourceRepair(schema,null).schema,schema);});

test('dashboard counts complete history even when the displayed list is capped',async()=>{
 const DB={prepare(sql){return {bind(){return this;},async all(){return {results:[]};},async first(){return sql.includes('COUNT(DISTINCT')?{attempts:150,skills:4}:{calls:0};}};}};
 const response=await worker.fetch(new Request('https://habla.test/api/dashboard?profile=luiz'),{LOCAL_DEV:'true',DB});
 assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.stats,{attempts:150,skills:4});assert.equal(data.attempts.length,0);
});
