import test from 'node:test';
import assert from 'node:assert/strict';
import {splitSpeech,cachedSpeech} from '../src/speech.js';
test('speech splitter preserves all content and stays under API input limit',()=>{const source=('Primera frase con un matiz importante. Segunda frase que conserva la objeción.\n\n').repeat(80).trim();const chunks=splitSpeech(source);assert.ok(chunks.length>1);assert.ok(chunks.every(c=>c.length<=4096));assert.equal(chunks.join(' ').replace(/\s+/g,' '),source.replace(/\s+/g,' '));});
test('a short source is not split and empty input is refused',()=>{assert.deepEqual(splitSpeech(' Una sola frase. '),['Una sola frase.']);assert.throws(()=>splitSpeech(' '));});
test('incomplete cached audio is never delivered as a complete file',async()=>{const db={prepare:sql=>({bind:()=>({first:async()=>({mime:'audio/mpeg',bytes:5,data:new Uint8Array([1,2]),cache_token:'x'}),all:async()=>({results:[{data:new Uint8Array([3])}]})})})};assert.equal(await cachedSpeech(db,'id'),null);});

import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {prepareSpeech} from '../src/speech.js';
function audioDB(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const name of readdirSync(new URL('../migrations/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));const db={sqlite,prepare(sql){let args=[];const stmt={bind(...values){args=values.map(v=>v instanceof ArrayBuffer?new Uint8Array(v):v);return stmt;},first:async()=>sqlite.prepare(sql).get(...args)||null,all:async()=>({results:sqlite.prepare(sql).all(...args)}),run:async()=>sqlite.prepare(sql).run(...args)};return stmt;},async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return db;}
function seedAudioTask(db,id='audio-task'){const row={id,profile_id:'luiz',kind:'listening',title:'Escuta',payload:JSON.stringify({source:'Una fuente breve pero completa.'})};db.sqlite.prepare('INSERT INTO tasks(id,profile_id,kind,title,payload) VALUES (?,?,?,?,?)').run(row.id,row.profile_id,row.kind,row.title,row.payload);return row;}
test('voice cache is reused, incomplete cache is repaired and lock is released',async()=>{const db=audioDB(),row=seedAudioTask(db);let calls=0;const synth=async()=>{calls++;return new Uint8Array([1,2,3,4]).buffer;};const first=await prepareSpeech({DB:db},row,synth);assert.equal(first.cache,'miss');assert.equal((await prepareSpeech({DB:db},row,synth)).cache,'hit');assert.equal(calls,1);db.sqlite.prepare('UPDATE generated_audio SET bytes=50 WHERE task_id=?').run(row.id);const repaired=await prepareSpeech({DB:db},row,synth);assert.equal(repaired.cache,'miss');assert.equal(calls,2);assert.equal((await cachedSpeech(db,row.id)).bytes.byteLength,4);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM speech_locks').get().n,0);});
test('simultaneous voice requests synthesize once and cache quota never grows above cap',async()=>{const db=audioDB(),row=seedAudioTask(db);let release;const gate=new Promise(r=>release=r);let calls=0;const first=prepareSpeech({DB:db},row,async()=>{calls++;await gate;return new Uint8Array([1,2,3,4]).buffer;});await new Promise(r=>setTimeout(r,0));await assert.rejects(prepareSpeech({DB:db},row,async()=>{calls++;return new Uint8Array([1]).buffer;}),e=>e.status===409);release();await first;assert.equal(calls,1);const second=seedAudioTask(db,'other');db.sqlite.prepare('UPDATE generated_audio SET bytes=100000000 WHERE task_id=?').run(row.id);const response=await prepareSpeech({DB:db},second,async()=>new Uint8Array([5,6]).buffer);assert.equal(response.cache,'uncached');assert.equal(await cachedSpeech(db,second.id),null);assert.equal(db.sqlite.prepare('SELECT SUM(bytes) AS n FROM generated_audio').get().n,100000000);});
